[package]
name = "control-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.209", features = ["serde_derive"] }
serde_json = "1.0.127"
nalgebra = { version = "0.33.0", features = ["serde-serialize"] }
num-traits = "0.2.19"
plotly = "0.10.0"


[dev-dependencies]
csv = "1.3.0"
rand = "0.8.5"
rand_distr = "0.4.3"