name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Check formatting
      run: cargo fmt --all -- --check || (echo "Run 'cargo fmt --all' locally to fix formatting" && exit 1)

    - name: Run clippy
      run: cargo clippy -- -D warnings

    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
  publish:
    runs-on: ubuntu-latest
    needs: build # Ensures build and test pass before publishing
    
    # Only run this job when a new tag starting with 'v' is pushed
    # (e.g., v1.0.0, v1.2.3-alpha)
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4

      - name: Log in to crates.io
        # This uses a repository secret to authenticate
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
        
      - name: Publish to crates.io
        run: cargo publish
